version: "1.0"

networks:
  jdb:
    external: false

services:
  bootstrap-node:
    hostname: bootstrap-node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    restart: on-failure
    ports:
      - '3001:3001'

  node2:
    hostname: node2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    restart: on-failure
    ports:
      - '3002:3001'

  node3:
    hostname: node3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    restart: on-failure
    ports:
      - '3003:3001'

  node4:
    hostname: node4
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    restart: on-failure
    ports:
      - '3004:3001'

  node5:
    hostname: node5
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    restart: on-failure
    ports:
      - '3005:3001'