version: "1.0"

networks:
  jdb:
    external: false

services:
  zk:
    hostname: zookeeper
    image: zookeeper:3.5.8
    ports:
      - "2181:2181"
    networks:
      - jdb

  bootstrap-node:
    hostname: bootstrap-node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    restart: on-failure
    ports:
      - '3001:3001'
    networks:
      - jdb
    depends_on:
      - zk

  node2:
    hostname: node2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    restart: on-failure
    ports:
      - '3002:3001'
    networks:
      - jdb
    depends_on:
      - zk


  node3:
    hostname: node3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    restart: on-failure
    ports:
      - '3003:3001'
    networks:
      - jdb
    depends_on:
      - zk

  node4:
    hostname: node4
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    restart: on-failure
    ports:
      - '3004:3001'
    networks:
      - jdb
    depends_on:
      - zk

  node5:
    hostname: node5
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    restart: on-failure
    ports:
      - '3005:3001'
    networks:
      - jdb
    depends_on:
      - zk